name: Build with Quality Check
on:
  push:
    branches:
      - "*"
  workflow_call:

jobs:
  shellcheck:
    uses: ./.github/workflows/shellcheck.yml
  build:
    uses: ./.github/workflows/build-deb.yml
    needs: shellcheck
